backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["Analytics", "Cloudflare"]
        add_to_top: true
        allow_add: true
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Navigation Caption", name: "navtitle", widget: "string", default: {{ title }}, required: false }
      - {label: "Add to Navigation", name: "navigation", widget: "boolean", default: false}
      - {label: "Add to Footer", name: "footer", widget: "boolean", default: false}
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Blog Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
